In [3]:
import numpy as np

Creating Array from List

In [ ]:

arr_1d=np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print("2D array:",arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3 4]
 [5 6 7 8]]


List vs Numpy

In [ ]:

py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array=np.array([1,2,3])
print("Python array multiplication:",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time:",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n numpy operation time:",time.time()-start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication: [2 4 6]

 List operation time: 0.047411203384399414

 numpy operation time: 0.0036373138427734375


Creating Array From Scratch

In [ ]:

zero=np.zeros([3,4])
print("zeros array:\n",zero)

ones=np.ones([3,4])
print("ones array:\n",ones)

full=np.full([3,4],7)
print("full array:\n",full)

random = np.random.random((2, 3))
print("random array: \n", random)

squence=np.arange(0,11,2)
print("squence array:\n",squence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array: 
 [[0.66528789 0.94489137 0.42749294]
 [0.93167786 0.21002793 0.90792696]]
squence array:
 [ 0  2  4  6  8 10]


Vector,Matrix and Tensor

In [ ]:

vector=np.array([1,2,3])
print("vector:\n",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print('matrix:\n',matrix)

tensor=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print("Tensor:\n",tensor)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


Array Properties

In [ ]:

arr=np.array([[1,2,3],[4,5,6]])

print("shape:",arr.shape)
print("Dimension:",arr.ndim)
print("size:",arr.size)
print("Dtype:",arr.dtype)


shape: (2, 3)
Dimension: 2
size: 6
Dtype: int64


Array Reshaping

In [ ]:

arr=np.arange(12)
print("\n original array:",arr)

reshaped=arr.reshape([3,4])
print("\n Reshaped:",reshaped)

flattened = reshaped.flatten()
print("\nFlattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)


 original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
