Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 0])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element 4
Entire row:  [4 5 6]
Entire column:  [2 5 8]


Sorting

In [5]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("\nsorted:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0)) # column wise

unsorted2=np.array([[2,3,1],[4,6,5],[9,8,7]])
print(unsorted2)
print("\n sorted in 2D:",np.sort(unsorted2,axis=1)) # row wise
print("\n sorted in 2D:",np.sort(unsorted2,axis=0)) # column wise


sorted: [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
[[2 3 1]
 [4 6 5]
 [9 8 7]]

 sorted in 2D: [[1 2 3]
 [4 5 6]
 [7 8 9]]

 sorted in 2D: [[2 3 1]
 [4 6 5]
 [9 8 7]]


Filter

In [11]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number=numbers[numbers%2==0]
print("even number:",even_number)

odd_number=numbers[numbers%2!=0]
print("odd number:",odd_number)


# filter with mask
mask=numbers>5 
print("Numbers greater than 5:",numbers[mask])


# fancy indexing vs np.where()
indices=[0,2,4]
print("indices:",numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("NP where:",numbers[where_result])

condition_array=np.where(numbers>5,"True","False")
print(condition_array)

even number: [ 2  4  6  8 10]
odd number: [1 3 5 7 9]
Numbers greater than 5: [ 6  7  8  9 10]
indices: [1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


Adding and Removing

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

new_arr=np.delete(arr2,1)
print(new_arr)

[1 2 3 4 5 6]
[4 6]


Array compatibility

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
with_new_row=np.vstack((original,new_row))
print("\noriginal:",original)
print("\nafter new roe:",with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("\n after new column:",with_new_col)

Compatibility shapes False

original: [[1 2]
 [3 4]]

after new roe: [[1 2]
 [3 4]
 [5 6]]

 after new column: [[1 2 7]
 [3 4 8]]
